"""add_image_fields_to_post

Revision ID: 194178a3363a
Revises: 2eeb600f26b0
Create Date: 2025-05-21 19:02:55.655374

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '194178a3363a'
down_revision = '2eeb600f26b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_path', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('image_url', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('image_url')
        batch_op.drop_column('image_path')

    # ### end Alembic commands ###
